# docker-compose.yml file

version: '3.6'

services:
  server:
    build: ./server
    volumes:
      - type: bind
        source: ./server/
        target: /usr/app
    ports:
      - 3001:3001
    command: npm run install_and_run
  search_service:
    build: ./search-service
    dockerfile: Dockerfile-dev
    volumes:
      - type: bind
        source: ./search-service/
        target: /usr/app
    depends_on:
      - elasticsearch
    links: 
      - elasticsearch
    ports:
      - 3009:3009
    command: npm run install_and_run
  web_ui:
    build: ./web-ui
    dockerfile: Dockerfile-dev
    volumes:
      - type: bind
        source: ./web-ui/
        target: /usr/app
    ports:
      - 3003:3003
    command: npm run start
  auth_service:
    build: ./auth-service
    volumes:
      - type: bind
        source: ./auth-service/
        target: /usr/app
    depends_on:
      - elasticsearch
    links: 
      - elasticsearch
    ports:
      - 3010:3010
    command: npm run install_and_run
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    environment:
      - discovery.type=single-node
    ports:
      - 9300:9300
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    # volumes:
    #   - ./kibana.yml:/usr/share/kibana/config/kibana.yml
  rabbitmq:
    image: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

