# docker-compose.yml file

version: '3.6'

services:
  search_service:
    build:
      context: ./search-service
      dockerfile: Dockerfile-dev
    volumes:
      - type: bind
        source: ./search-service/
        target: /usr/app
    depends_on:
      - elasticsearch
    links: 
      - elasticsearch
    ports:
      - 3009:3009
    command: npm run install_and_run
  web_ui:
    build:
      context: ./web-ui
      dockerfile: Dockerfile-dev
    volumes:
      - type: bind
        source: ./web-ui/
        target: /usr/app
    ports:
      - 3003:3003
    command: npm run start
  auth_service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile-dev
    volumes:
      - type: bind
        source: ./auth-service/
        target: /usr/app
    depends_on:
      - elasticsearch
    links: 
      - elasticsearch
    ports:
      - 3010:3010
    command: npm run install_and_run
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    environment:
      - discovery.type=single-node
    ports:
      - 9300:9300
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
  rabbitmq:
    image: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: w3lc0me!
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080    

