# FROM node:13.6
# WORKDIR /usr/app
# COPY package.json .
# RUN npm install --quiet

# COPY . .
# CMD ["npm", "start"]
FROM node:13.6
WORKDIR /usr/app
# COPY package.json .
# RUN npm install

# COPY . .