name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env: auth-service
    steps:
    - uses: actions/checkout@v2
    - name: Running linter
      run: yarn run lint
    # - name: Build the Auth service Docker image and publish to GitHub Packages
    #   run: |
    #     docker build ./$SERVICE_NAME --file ./$SERVICE_NAME/Dockerfile --tag docker.pkg.github.com/brainbackup/bb8/$SERVICE_NAME:$VERSION
    #     docker login docker.pkg.github.com --username ynahmany --password ${{ secrets.GITHUB_TOKEN }}
    #     docker push docker.pkg.github.com/brainbackup/bb8/$SERVICE_NAME:$VERSION
