name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./auth-service
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: yarn
      working-directory: ${{ env.working-directory }}
    - name: Running linter
      run: yarn run lint
      working-directory: ${{ env.working-directory }}
    - name: Running Unit tests
      run: yarn run test
      working-directory: ${{ env.working-directory }}
    - name: Running e2e tests
      run: yarn run test:e2e
      working-directory: ${{ env.working-directory }}
    - name: Running tests coverage
      run: yarn run test:cov
      working-directory: ${{ env.working-directory }}
    - name: Build the Auth service Docker image and publish to GitHub Packages
      working-directory: ${{ env.working-directory }}
      run: |
        docker build . --tag docker.pkg.github.com/brainbackup/bb8/auth-service:$VERSION
        docker login docker.pkg.github.com --username ynahmany --password ${{ secrets.GITHUB_TOKEN }}
        docker push docker.pkg.github.com/brainbackup/bb8/auth-service:$VERSION
