name: NPM packages

on: [push]

jobs:

  publish-gpr:
    runs-on: ubuntu-latest
    env:
        working-directory: ./types
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 12
            registry-url: https://npm.pkg.github.com/
        - run: |
            ls -la
            npm publish
          env:
            NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
            working-directory: ${{ env.working-directory }}
